before_script:
  - chmod u+x ./rebar3

language: erlang
otp_release:
  - 20.0
  - 19.1
  - 18.3


stages:
  - build
  - test
##  - deploy

build:
  stage: build
  only:
    - master
    - develop
  script:
    - ./rebar3 upgrade
    - ./rebar3 compile

test:
  stage: test
  only:
    - master
  except:
    - tags
  script:
    - ./rebar3 as test eunit