before_script:
  - chmod u+x ./rebar3

language: erlang
otp_release:
  - 20.0
  - 19.1
  - 18.3

#jobs:
#  include:
#    - stage: test
#      script:
#        - ./rebar3 upgrade
#        - ./rebar3 compile
#        - ./rebar3 eunit
#
#    - stage: deploy
#      script: true


stages:
#  - compile
  - test
  - deploy

#compile:
#  stage: compile
#  only:
#    - master
#    - develop
#  script:
#    - ./rebar3 upgrade
#    - ./rebar3 compile

test:
  stage: test
  only:
    - master
  except:
    - tags
  script:
    - ./rebar3 upgrade
    - ./rebar3 compile
    - ./rebar3 as test eunit

deploy:
  stage: deploy
  script:
    skip