before_script:
#  - "chmod u+x ./rebar3"
  - "rebar3 upgrade"

language: erlang
otp_release:
  - 20.0
  - 19.1
  - 18.3

jobs:
  include:
#    - stage: eunit
#      script:
#        - "./rebar3 compile"
#        - "./rebar3 eunit"
    - stage: common_test
      script:
        - "rebar3 ct"
    - stage: deploy
      script: true

#
#stages:
#  - test
#  - common_test
##  - deploy
#
#
#test:
#  stage: test
#  only:
#    - master
#  except:
#    - tags
#  script:
#    - ./rebar3 upgrade
#    - ./rebar3 compile
#    - ./rebar3 as test eunit
#
#common_test:
#  stage: common_test
#  script:
#    - ./rebar3 ct
#
#deploy:
#  stage: deploy
#  script:
#    skip